name: gh-action
on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          pip install -r requirements.txt
          pip install ".[test]"

      - name: Run tests
        run: pytest tests

      - name: Build python package
        run: |
          python3 -m pip install --upgrade build
          python3 -m build
          cp dist /tmp/dist

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build model serving docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          tags: "marvelousmlops/dagger_example:latest"
